### ISSUE TITLE
None of the plugin commands work

### ISSUE THREAD

**Issue by pawelkw** [timstrasser/Pico-Go#3]
## What are the steps to reproduce this issue?
1. Create new project with a hello world Python file.
2. Try to run "Pico-Go > Configure project"
3. 

## What happens?
Error message pops up. Same error for other commands.

## What were you expecting to happen?
Project gets configured correctly. Other commands work too.

## Any logs, error output, etc?
<img width="269" alt="image" src="https://user-images.githubusercontent.com/1320997/178118934-bf71f34f-8edf-4817-b8db-f25d9743d0c0.png">

## Any other comments?
I use version 1.4.5 of the extension.
VS Code info:
```
Version: 1.69.0
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:46.408Z (2 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
```
I'm on a M1 Mac if that matters.

## Support info

Copy this from the `Pico-Go > Help > Get support info` option in the command palette:
I can't, I get the same error:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1320997/178119009-bf0a91e6-8c9d-4e9a-96a8-4dee29215688.png">

**Comment by rasmusthog** [comment]
@pawelkw As per Felix' suggestion under Discussions, you can downgrade VS Code if that is an option for you. I had the same issue as you until I went back to 1.58.2, then it worked like a charm. 

Do you also get an error saying it could not load due to not finding certain folders in Pico-Go/node_packages/@serialport/bindings?

**Comment by timstrasser** [comment]
I think to resolve this issue, new bindings need to be built for the current version of VS Code, however I was not yet able to do that. You should be able to see the logs here:
https://github.com/timstrasser/Bindings-Builder/runs/7284048083

In case anyone can help, I would appreciate that.
